### ISSUE TITLE
[Feature Request] Change Elasticsearch Status to Green

### ISSUE THREAD

**Issue by peasead** [thremulation-station/thremulation-station#13]
**Is your feature request related to a problem? Please describe.**
We can make a single API call to set the replica status of Elasticsearch to `0` and make the cluster `green` vs. having to explain `yellow`.

**Describe the solution you'd like**
We can do it via an API call in the packer build. 
```
curl -X PUT "localhost:9200/*/_settings?pretty" -H 'Content-Type: application/json' -d'
{
  "index" : {
    "number_of_replicas" : 0
  }
}
'
```

I **think** this can be done at `thremulation-station/packer/elastomic/ansible/elastomic-playbook.yml`
```
    - name: Update Elasticsearch Replica Status
      uri:
        url: "curl -H "Content-Type: application/json" -XPUT localhost:9200/*/_settings -d '{ "index" : { "number_of_replicas" : 0 } }'"
        status_code: 200
```

**Describe alternatives you've considered**
I explored making a change to `elasticsearch.yml` in `packer/elastomic/ansible/files/elasticsearch.yml`, but this is no longer a supported configuration in `elasticsearch.yml` [[1](https://discuss.elastic.co/t/setting-number-of-replicas-value-to-0-makes-the-cluster-unavailable/155083/2)].

**Additional context**
Before change
```
{
  "cluster_name": "elasticsearch",
  "status": "yellow",
  "timed_out": false,
  "number_of_nodes": 1,
  "number_of_data_nodes": 1,
  "active_primary_shards": 14,
  "active_shards": 14,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 3,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 82.35294117647058
}
```

Post-change
```
{
  "cluster_name": "elasticsearch",
  "status": "green",
  "timed_out": false,
  "number_of_nodes": 1,
  "number_of_data_nodes": 1,
  "active_primary_shards": 14,
  "active_shards": 14,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 0,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 100
}
```
